version: '3.1'
services:
  stats-server:
    image: statistics-service
    build: statistics/service
    ports:
      - "9090:9090"
    depends_on:
    - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-with-me-stats
      - POSTGRES_DB=explore-with-me-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
